### ISSUE TITLE
Sanitizing column names

### ISSUE THREAD

**Issue by XF-FW** [tomwojcik/is_valid_postgres_column#1]
Hey, found this cool library. Thank you for your work. 

Would you accept a PR (in the future, currently a bit busy with work), that includes some kind of sanitization of a given column name?

I was thinking, a great property to have for the sanitization would be that it hopefully reduces possible collisions with existing columns, but I'm not completely sure on how to do that.

Your input would be greatly appreciated. Thanks!

**Comment by tomwojcik** [comment]
Hey, thank you very much. I'm glad it helped at least one person!

You're talking about two different things. Sanitization of the column name is already provided by regex. 

As per collisions with existing columns within a single table, I think that's out of the scope for this library.

Anyway, for listing already existing column names in a table, I use this

```python
def get_column_names(table_name: str) -> List[str]:
    stmt = (
        f"SELECT column_name "
        f"FROM information_schema.columns "
        f"WHERE table_schema='public' "
        f"AND table_name='{table_name}';"
    )

    with connection.cursor() as cur:
        cur.execute(stmt)
        return [r[0] for r in cur.fetchall()]
```

so you can just `column_name in get_column_names(table_name)`.



Does that answer your question?

**Comment by XF-FW** [comment]
Hey there. I'm sorry, but it doesn't really answer my question. It's my fault really. I just didn't explain my problem properly.  
I'm going to expose my use-case to make things clearer:

Let's say I have a table called rows, with an attribute called `data`. This is a JSONField with arbitrary and dynamic keys. Sometimes, I need to calculate the sum of a given key for a subset of the table. For reference only, the following code, written with Django-ORM, is roughly what I had:

```
keys = ["column", "a column with whitespace"]
annotations = {}
aggregations = {}
for key in keys:
    db_column_name = f"data_{key}"

    annotations[db_column_name] = Cast(
        m.fields.json.KeyTextTransform(key, "data"),
        m.IntegerField(),
    )

    aggregations[key] = Coalesce(m.Sum(db_column_name), 0)

return qs.annotate(**annotations).aggregate(**aggregations)
```

Now, the issue with this code in particular is that the keys are free text, however they're used here as column names. This triggers a Django error:
```
ValueError: Column aliases cannot contain whitespace characters, quotation marks, semicolons, or SQL comments.
```

I searched and found this library, when I got the error above.

I would say to forget the Django stuff, but while typing this, I commented out the django bit that did that validation and after running the tests, it appears that no errors in postgres is actually raised. So, I might have made a wrong assumption, that this was an issue with postgres column names. I'm assuming however, there are some strings, that would indeed, trigger an error with postgres. I've only tried adding whitespaces.

I posted this issue, with the intention, of maybe having a function in this package, that I could wrap the `key` variable in the example above, with a hypothetical, `sanitize_column_name`, so that the example above worked without any fuss. 

The bit about the collisions: I wanted that the hypothetical sanitizing function, would try to create distinct column names, not unlike a hash function, although I realize that's a tall ask. For example, let's say, I create a sanitizing function, that just removes whitespace, not unlike `lambda col: col.replace(' ', '')`. This might be an issue for my use case, as I might have a key called `acolumn` and another `a column`, and the resulting string after sanitization is the same. 

Now, I've solved my issue, by enumerating `keys` and using the index as the column alias, bypassing the need to for any kind of sanitization. Tbh, I think it's the better solution, although it makes inspecting the resulting SQL query a bit of a pain.

Regarding this issue, I'm closing it, because I don't feel a need to have that `sanitize_column_name` function anymore and I'm not sure if it falls under the goal of this project.

Once again, I apologize for not explaining things properly the first time.  
Thank you for your time!

**Comment by tomwojcik** [comment]
I see, so your use case is definitely more complicated than I initially thought.

This commit https://github.com/django/django/commit/93cae5cb2f9a4ef1514cf1a41f714fef08005200 introduces the fix for a CVE. I think it indeed might help to prevent SQL injection, though you should be able to insert it as you desire using raw SQL. But then you need to handle SQL injection yourself.

To sum up, Django introduced a change that hardens it against SQL injection but it's not really related to validating column names, but rather some potential holes in the ORM. You could pass your own pattern 

https://github.com/tomwojcik/is_valid_postgres_column_name/blob/1ad53188acdc586e2a27707dd9ff06951e4ca56a/is_valid_postgres_column_name/main.py#L41-L44

that will also check against Django [column alias pattern](https://github.com/django/django/blob/49b470b9187b6be60e573fed08c8f4a87f133750/django/db/models/sql/query.py#L51) but I'm not sure that's something you want as column alias != column name.

Good luck!
